language: go

go:
    - "1.10"
    - "1.11.x"
    - "1.12.x"
    - master

os:
  - linux
  - osx

sudo: false

before_install:
    - go get golang.org/x/lint/golint
    - go get -d -t ./...

script:
    - go vet ./...
    - golint -set_exit_status ./...
    - go test -v -race ./...
    - go test -c -tags integration .
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ./go-conntrack.test -test.v ; fi
