language: go

go:
    - "1.9"
    - "1.10"
    - "1.11.x"
    - master

os:
  - linux
  - osx

sudo: false

before_install:
    - go get golang.org/x/lint/golint
    - go get -t ./...

script:
    - go vet ./...
    - golint -set_exit_status ./...
    - go test -v -race ./...
